databases:
  library_db:
    user: postgres
    password: password
    db: libraries
    host: postgres_db
    port: 5432
  rating_db:
    user: postgres
    password: password
    db: ratings
    host: postgres_db
    port: 5432
  reservation_db:
    user: postgres
    password: password
    db: reservations
    host: postgres_db
    port: 5432

services:
  library:
    host: "0.0.0.0"
    port: 8060
    log_level: "info"
    reload: True
  rating:
    host: "0.0.0.0"
    port: 8050
    log_level: "info"
    reload: True
  reservation:
    host: "0.0.0.0"
    port: 8070
    log_level: "info"
    reload: True
  # gateway:
  #   host: "0.0.0.0"
  #   port: 8080
  #   log_level: "info"
  #   reload: True
  #   bonus_host:  bonus_service
  #   flight_host: flight_service
  #   ticket_host: ticket_service
