version: '3.1'

services:
  library_database:
    image: postgres:16-alpine
    container_name: library_database
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library_db
    volumes:
      - ./pg_data_library:/var/lib/postgresql/data
      - ./src/library_service/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  library_service:
    image: library_service
    container_name: library_service
    build:
      context: "."
      dockerfile: ./docker/library.Dockerfile
    ports:
      - "8060:8060"
    networks:
      - default
    depends_on:
      library_database:
        condition: service_healthy



volumes:
  pg_data_library:
    driver: local
  # pg_data_bonus:
  #   driver: local
  # pg_data_flight:
  #   driver: local

networks:
  default:
